// Code generated by generate-client. DO NOT EDIT.

package {{ .Package.Name }}

import (
    {{- range $name, $group := .Groups }}
    {{ $group.Package.Alias }} {{ $group.Package.Path | quote }}
    {{- end }}
    "github.com/onosproject/helm-go/pkg/kubernetes/config"
    "github.com/onosproject/helm-go/pkg/kubernetes/resource"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/kubernetes"
)

// New returns a new Kubernetes client for the current namespace
func New() (Client, error) {
	return NewForNamespace(config.GetNamespaceFromEnv())
}

// NewOrDie returns a new Kubernetes client for the current namespace
func NewOrDie() Client {
	client, err := New()
	if err != nil {
		panic(err)
	}
	return client
}

// NewForNamespace returns a new Kubernetes client for the given namespace
func NewForNamespace(namespace string) (Client, error) {
	kubernetesConfig, err := config.GetRestConfig()
	if err != nil {
		return nil, err
	}
	kubernetesClient, err := kubernetes.NewForConfig(kubernetesConfig)
	if err != nil {
    	return nil, err
	}
    return &{{ .Types.Struct }}{
        namespace: namespace,
        config:    kubernetesConfig,
        client:    kubernetesClient,
        filter:    resource.NoFilter,
    }, nil
}

// NewForNamespaceOrDie returns a new Kubernetes client for the given namespace
func NewForNamespaceOrDie(namespace string) Client {
	client, err := NewForNamespace(namespace)
	if err != nil {
		panic(err)
	}
	return client
}

// {{ .Types.Interface }} is a Kubernetes client
type {{ .Types.Interface }} interface {
	// Namespace returns the client namespace
	Namespace() string

	// Config returns the Kubernetes REST client configuration
	Config() *rest.Config

	// Clientset returns the client's Clientset
	Clientset() *kubernetes.Clientset

    {{- range $name, $group := .Groups }}
    {{ $group.Names.Proper }}() {{ $group.Package.Alias }}.{{ $group.Types.Interface }}
    {{- end }}
}

// NewFiltered returns a new filtered Kubernetes client
func NewFiltered(namespace string, filter resource.Filter) ({{ .Types.Interface }}, error) {
	kubernetesConfig, err := config.GetRestConfig()
	if err != nil {
		return nil, err
	}
	kubernetesClient, err := kubernetes.NewForConfig(kubernetesConfig)
	if err != nil {
		return nil, err
	}
	return &{{ .Types.Struct }}{
		namespace: namespace,
		config:    kubernetesConfig,
		client:    kubernetesClient,
		filter:    filter,
	}, nil
}

// NewFilteredOrDie returns a new filtered Kubernetes client
func NewFilteredOrDie(namespace string, filter resource.Filter) {{ .Types.Interface }} {
	client, err := NewFiltered(namespace, filter)
	if err != nil {
		panic(err)
	}
	return client
}

type {{ .Types.Struct }} struct {
	namespace string
	config    *rest.Config
	client    *kubernetes.Clientset
	filter    resource.Filter
}

func (c *{{ .Types.Struct }}) Namespace() string {
	return c.namespace
}

func (c *{{ .Types.Struct }}) Config() *rest.Config {
	return c.config
}

func (c *{{ .Types.Struct }}) Clientset() *kubernetes.Clientset {
	return c.client
}

{{- range $name, $group := .Groups }}
func (c *{{ .Types.Struct }}) {{ $group.Names.Proper }}() {{ $group.Package.Alias }}.{{ $group.Types.Interface }} {
    return {{ $group.Package.Alias }}.New{{ $group.Types.Interface }}(c, c.filter)
}
{{ end }}
